
import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author admin
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    private NhanVienManager nvManager;
    private DefaultTableModel tableModel;

    public FormMain() {
        initComponents();
        nvManager = new NhanVienManager();
        tableModel = (DefaultTableModel) tblNhanVien.getModel();
        loadTableData(); // Tải dữ liệu ban đầu vào bảng
    }

    private void loadTableData() {
        tableModel.setRowCount(0); // Xóa tất cả dữ liệu trong bảng
        List<NhanVien> list = nvManager.getAllNhanVien();
        for (NhanVien nv : list) {
            Object[] row = {
                nv.getMaNhanVien(),
                nv.getTenNhanVien(),
                nv.getBoPhan(),
                nv.getChucVu(),
                nv.getGioiTinh(),
                nv.getEmail(),
                nv.getSoDienThoai()
            };
            tableModel.addRow(row);
        }
    }

    // Phương thức tải lại dữ liệu bảng
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slidebarpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuqlnv = new javax.swing.JLabel();
        menuchamcong = new javax.swing.JLabel();
        menutinhluong = new javax.swing.JLabel();
        menucdpl = new javax.swing.JLabel();
        btnDangxuat = new javax.swing.JButton();
        contentpanel = new javax.swing.JPanel();
        qlnvpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnHienThi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtManv = new javax.swing.JTextField();
        txtTennv = new javax.swing.JTextField();
        txtBophan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcomboxGioiTinh = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSodienthoai = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtManvTimKiem = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        chamcongpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcomboxChonnv = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableChamcong = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtGiovao = new javax.swing.JTextField();
        txtgiora = new javax.swing.JTextField();
        btnChamvao = new javax.swing.JButton();
        btnChamra = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        tinhluongpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableLuong = new javax.swing.JTable();
        cdplpanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hệ thống quản lý nhân viên");

        menuqlnv.setText("Quản lý nhân viên");
        menuqlnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuqlnvMouseClicked(evt);
            }
        });

        menuchamcong.setText("Chấm công");
        menuchamcong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuchamcongMouseClicked(evt);
            }
        });

        menutinhluong.setText("Tính lương");
        menutinhluong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menutinhluongMouseClicked(evt);
            }
        });

        menucdpl.setText("Chế độ phúc lợi");
        menucdpl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menucdplMouseClicked(evt);
            }
        });

        btnDangxuat.setText("Đăng xuất");
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout slidebarpanelLayout = new javax.swing.GroupLayout(slidebarpanel);
        slidebarpanel.setLayout(slidebarpanelLayout);
        slidebarpanelLayout.setHorizontalGroup(
            slidebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slidebarpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(slidebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menucdpl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menutinhluong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuchamcong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuqlnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(slidebarpanelLayout.createSequentialGroup()
                        .addComponent(btnDangxuat)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        slidebarpanelLayout.setVerticalGroup(
            slidebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slidebarpanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuqlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuchamcong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menutinhluong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menucdpl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDangxuat)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        contentpanel.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Quản lý nhân viên");

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Bộ phận", "Chức năng", "Giới tính", "Email", "Điện thoại"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNhanVien);

        btnHienThi.setText("Hiển Thị");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel6.setText("Mã nhân viên");

        jLabel7.setText("Tên nhân viên");

        jLabel8.setText("Bộ phận");

        jLabel9.setText("Chức Vụ");

        jLabel10.setText("Giới tính");

        jcomboxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jLabel11.setText("Email");

        jLabel12.setText("Điện thoại");

        jLabel13.setText("Mã nhân viên");

        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(txtManvTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimkiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHuy)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(btnTimkiem)
                    .addComponent(btnHuy)
                    .addComponent(txtManvTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout qlnvpanelLayout = new javax.swing.GroupLayout(qlnvpanel);
        qlnvpanel.setLayout(qlnvpanelLayout);
        qlnvpanelLayout.setHorizontalGroup(
            qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qlnvpanelLayout.createSequentialGroup()
                .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qlnvpanelLayout.createSequentialGroup()
                        .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHienThi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(qlnvpanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnThem)
                                .addGap(28, 28, 28)
                                .addComponent(btnSua))
                            .addGroup(qlnvpanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoa)
                            .addGroup(qlnvpanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcomboxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(qlnvpanelLayout.createSequentialGroup()
                        .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(qlnvpanelLayout.createSequentialGroup()
                                .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(qlnvpanelLayout.createSequentialGroup()
                                        .addComponent(txtBophan, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(qlnvpanelLayout.createSequentialGroup()
                                .addComponent(txtTennv, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSodienthoai, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEmail)))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(qlnvpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE))))
                .addContainerGap())
        );
        qlnvpanelLayout.setVerticalGroup(
            qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qlnvpanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHienThi)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jcomboxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBophan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(txtSodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(qlnvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
        );

        contentpanel.add(qlnvpanel, "qlnvpanel");

        jLabel3.setText("Chấm Công");

        jLabel14.setText("Chọn nhân viên");

        jcomboxChonnv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcomboxChonnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboxChonnvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jcomboxChonnv, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jcomboxChonnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tableChamcong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ngày ", "Giờ vào", "Giờ ra", "Số giờ làm"
            }
        ));
        jScrollPane1.setViewportView(tableChamcong);

        jLabel15.setText("Giờ vào");

        jLabel16.setText("Giờ ra");

        btnChamvao.setText("Chấm vào");

        btnChamra.setText("Chấm ra");

        jLabel17.setText("Ngày chấm công");

        javax.swing.GroupLayout chamcongpanelLayout = new javax.swing.GroupLayout(chamcongpanel);
        chamcongpanel.setLayout(chamcongpanelLayout);
        chamcongpanelLayout.setHorizontalGroup(
            chamcongpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(chamcongpanelLayout.createSequentialGroup()
                .addGroup(chamcongpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(chamcongpanelLayout.createSequentialGroup()
                        .addGroup(chamcongpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(chamcongpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGiovao)
                            .addComponent(txtgiora, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(chamcongpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnChamvao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChamra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(chamcongpanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        chamcongpanelLayout.setVerticalGroup(
            chamcongpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chamcongpanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chamcongpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtGiovao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChamvao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chamcongpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtgiora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChamra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chamcongpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
        );

        contentpanel.add(chamcongpanel, "chamcongpanel");

        jLabel4.setText("Lương");

        jLabel19.setText("Chọn tháng tính lương");

        tableLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Tổng", "Lương", "Tháng"
            }
        ));
        jScrollPane3.setViewportView(tableLuong);

        javax.swing.GroupLayout tinhluongpanelLayout = new javax.swing.GroupLayout(tinhluongpanel);
        tinhluongpanel.setLayout(tinhluongpanelLayout);
        tinhluongpanelLayout.setHorizontalGroup(
            tinhluongpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tinhluongpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tinhluongpanelLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tinhluongpanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );
        tinhluongpanelLayout.setVerticalGroup(
            tinhluongpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tinhluongpanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tinhluongpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jMonthChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentpanel.add(tinhluongpanel, "tinhluongpanel");

        jLabel5.setText("Chế độ phúc lợi");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel18.setText("Bảo hiểm");

        javax.swing.GroupLayout cdplpanelLayout = new javax.swing.GroupLayout(cdplpanel);
        cdplpanel.setLayout(cdplpanelLayout);
        cdplpanelLayout.setHorizontalGroup(
            cdplpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cdplpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cdplpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cdplpanelLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        cdplpanelLayout.setVerticalGroup(
            cdplpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cdplpanelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(449, Short.MAX_VALUE))
        );

        contentpanel.add(cdplpanel, "cdplpanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(slidebarpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slidebarpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuqlnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuqlnvMouseClicked
        // TODO add your9 handling code here:
        CardLayout cl = (CardLayout) contentpanel.getLayout();
        cl.show(contentpanel, "qlnvpanel");
    }//GEN-LAST:event_menuqlnvMouseClicked

    private void menuchamcongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuchamcongMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) contentpanel.getLayout();
        cl.show(contentpanel, "chamcongpanel");
    }//GEN-LAST:event_menuchamcongMouseClicked

    private void menutinhluongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutinhluongMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) contentpanel.getLayout();
        cl.show(contentpanel, "tinhluongpanel");
    }//GEN-LAST:event_menutinhluongMouseClicked

    private void menucdplMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menucdplMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) contentpanel.getLayout();
        cl.show(contentpanel, "cdplpanel");
    }//GEN-LAST:event_menucdplMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // Lấy giá trị từ các trường nhập liệu
            int maNhanVien = Integer.parseInt(txtManv.getText());  // Chuyển đổi từ String sang int
            String tenNhanVien = txtTennv.getText();
            String boPhan = txtBophan.getText();
            String chucVu = txtChucVu.getText();
            String gioiTinh = jcomboxGioiTinh.getSelectedItem().toString();
            String email = txtEmail.getText();
            String soDienThoai = txtSodienthoai.getText();

            // Gọi phương thức addNhanVien để thêm nhân viên vào cơ sở dữ liệu
            boolean isAdded = nvManager.addNhanVien(maNhanVien, tenNhanVien, boPhan, chucVu, gioiTinh, email, soDienThoai);

            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Nhân viên đã được thêm thành công!");
                loadTableData();  // Tải lại dữ liệu bảng
            } else {
                JOptionPane.showMessageDialog(this, "Thêm nhân viên không thành công!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên phải là một số nguyên hợp lệ!");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int selectedRow = tblNhanVien.getSelectedRow();
        if (selectedRow != -1) {
            try {
                int maNhanVien = (int) tblNhanVien.getValueAt(selectedRow, 0);  // Lấy MaNhanVien từ bảng
                String tenNhanVien = txtTennv.getText();
                String boPhan = txtBophan.getText();
                String chucVu = txtChucVu.getText();
                String gioiTinh = jcomboxGioiTinh.getSelectedItem().toString();
                String email = txtEmail.getText();
                String soDienThoai = txtSodienthoai.getText();

                boolean isUpdated = nvManager.updateNhanVien(maNhanVien, tenNhanVien, boPhan, chucVu, gioiTinh, email, soDienThoai);
                if (isUpdated) {
                    JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công!");
                    loadTableData();
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thất bại!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật dữ liệu! Vui lòng thử lại.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần sửa!");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = tblNhanVien.getSelectedRow();
        if (selectedRow != -1) {
            try {
                int maNhanVien = (int) tblNhanVien.getValueAt(selectedRow, 0);  // Lấy MaNhanVien từ bảng

                boolean isDeleted = nvManager.deleteNhanVien(maNhanVien);
                if (isDeleted) {
                    JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công!");
                    loadTableData();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa nhân viên thất bại!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa dữ liệu! Vui lòng thử lại.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xóa!");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        String searchQuery = txtManvTimKiem.getText();

        // Kiểm tra nếu người dùng nhập vào là một số nguyên (mã nhân viên)
        try {
            int searchMaNhanVien = Integer.parseInt(searchQuery);  // Nếu có thể chuyển đổi sang int
            List<NhanVien> searchResults = nvManager.searchNhanVien(searchMaNhanVien);  // Tìm kiếm theo mã nhân viên

            // Xóa tất cả dữ liệu trong bảng
            tableModel.setRowCount(0);

            // Thêm các dòng tìm thấy vào bảng
            for (NhanVien nv : searchResults) {
                Object[] row = {
                    nv.getMaNhanVien(),
                    nv.getTenNhanVien(),
                    nv.getBoPhan(),
                    nv.getChucVu(),
                    nv.getGioiTinh(),
                    nv.getEmail(),
                    nv.getSoDienThoai()
                };
                tableModel.addRow(row);
            }
        } catch (NumberFormatException e) {
            // Nếu không thể chuyển sang int, tìm kiếm theo tên hoặc bộ phận
            List<NhanVien> searchResults = nvManager.searchNhanVien(searchQuery);  // Tìm kiếm theo tên hoặc bộ phận

            // Xóa tất cả dữ liệu trong bảng
            tableModel.setRowCount(0);

            // Thêm các dòng tìm thấy vào bảng
            for (NhanVien nv : searchResults) {
                Object[] row = {
                    nv.getMaNhanVien(),
                    nv.getTenNhanVien(),
                    nv.getBoPhan(),
                    nv.getChucVu(),
                    nv.getGioiTinh(),
                    nv.getEmail(),
                    nv.getSoDienThoai()
                };
                tableModel.addRow(row);
            }
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        txtManvTimKiem.setText("");
        loadTableData(); // Load lại tất cả dữ liệu
    }//GEN-LAST:event_btnHuyActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        // Kiểm tra nếu có dòng được chọn trong bảng
        int selectedRow = tblNhanVien.getSelectedRow();

        // Nếu chọn một dòng, thực hiện lấy dữ liệu từ dòng đó
        if (selectedRow != -1) {
            // Lấy dữ liệu từ các cột trong dòng được chọn
            int maNhanVien = (int) tblNhanVien.getValueAt(selectedRow, 0);  // Cột 0: Mã nhân viên
            String tenNhanVien = (String) tblNhanVien.getValueAt(selectedRow, 1);  // Cột 1: Tên nhân viên
            String boPhan = (String) tblNhanVien.getValueAt(selectedRow, 2);  // Cột 2: Bộ phận
            String chucVu = (String) tblNhanVien.getValueAt(selectedRow, 3);  // Cột 3: Chức vụ
            String gioiTinh = (String) tblNhanVien.getValueAt(selectedRow, 4);  // Cột 4: Giới tính
            String email = (String) tblNhanVien.getValueAt(selectedRow, 5);  // Cột 5: Email
            String soDienThoai = (String) tblNhanVien.getValueAt(selectedRow, 6);  // Cột 6: Số điện thoại

            // Cập nhật các JTextField và JComboBox với giá trị từ dòng được chọn
            txtManv.setText(String.valueOf(maNhanVien));  // Chuyển đổi int sang String
            txtTennv.setText(tenNhanVien);
            txtBophan.setText(boPhan);
            txtChucVu.setText(chucVu);

            // Giới tính có thể là "Nam" hoặc "Nữ", hãy chọn đúng giá trị trong JComboBox
            jcomboxGioiTinh.setSelectedItem(gioiTinh);

            txtEmail.setText(email);
            txtSodienthoai.setText(soDienThoai);
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Formlogin login = new Formlogin();
        login.setVisible(true);
    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void jcomboxChonnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboxChonnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboxChonnvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChamra;
    private javax.swing.JButton btnChamvao;
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel cdplpanel;
    private javax.swing.JPanel chamcongpanel;
    private javax.swing.JPanel contentpanel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jcomboxChonnv;
    private javax.swing.JComboBox<String> jcomboxGioiTinh;
    private javax.swing.JLabel menucdpl;
    private javax.swing.JLabel menuchamcong;
    private javax.swing.JLabel menuqlnv;
    private javax.swing.JLabel menutinhluong;
    private javax.swing.JPanel qlnvpanel;
    private javax.swing.JPanel slidebarpanel;
    private javax.swing.JTable tableChamcong;
    private javax.swing.JTable tableLuong;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JPanel tinhluongpanel;
    private javax.swing.JTextField txtBophan;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGiovao;
    private javax.swing.JTextField txtManv;
    private javax.swing.JTextField txtManvTimKiem;
    private javax.swing.JTextField txtSodienthoai;
    private javax.swing.JTextField txtTennv;
    private javax.swing.JTextField txtgiora;
    // End of variables declaration//GEN-END:variables
}
